language: python
python:
    - '3.6'
services:
    - mysql
    - redis-server
    - memcached
cache:
  bundler: true
  pip: true
  directories:
    - node_modules
    - static/node_modules
install:
    - npm i
    - cd static
    - npm i
    - cd ..
    - bundle install
    - pip install -r requirements.txt
    - pip install codecov coverage
    - mysql -u root -e 'CREATE DATABASE ppcg;'
    
    # Setup travis config
    - cp config.default.py config.py
    - sed -i "s/MYSQL_USERNAME/root/" config.py
    - sed -i "s/MYSQL_PASSWORD//" config.py
    - sed -i "s/REDIS_PASSWORD//" config.py
    - sed -i "s/IMGUR_CLIENT_ID/$IMGUR_CLIENT_ID/" config.py
    
    - celery multi start w1 -A celery_server
script:
    - coverage run -m unittest discover tests -v -f
after_success:
    - codecov