language: python
python:
    - "3.6"
services:
    - mysql
    - redis-server
install:
    - npm i
    - cd static
    - npm i
    - cd ..
    - bundle install
    - pip install -r requirements.txt
    - mysql -u root -e 'CREATE DATABASE ppcg;'
    
    # Setup travis config
    - cp config.default.py config.py
    - sed -i "s/MYSQL_USERNAME/root/" config.py
    - sed -i "s/MYSQL_PASSWORD//" config.py
    - sed -i "s/REDIS_PASSWORD//" config.py
script:
    - python -m unittest discover tests -v
