language: python
python:
    - "3.6"
services:
    - mysql
    - redis-server
install:
    - npm i
    - cd static
    - npm i
    - cd ..
    - bundle install
    - pip install -r requirements.txt
    - mysql -u root -e 'CREATE DATABASE ppcg;'
script:
    - echo -e "\e[1:32mStarting Tests...\e[0m"
