language: python
services:
    - mysql
install:
    - npm i
    - bundle install
    - pip install -r requirements.txt
    - mysql -u root -e 'CREATE DATABASE ppcg;'
    - mysql -u root ppcg < ppcg.sql
