dist: xenial
language: python
python:
  - '3.6'
services:
  - mysql
  - redis-server
  - memcached
cache:
  bundler: true
  pip: true
  directories:
    - "$HOME/.npm"
install:
  - npm ci
  - bundle install
  - pip install -r requirements.txt
  - pip install codecov coverage
  - pip install httpie
  - mysql -u root -e 'CREATE DATABASE ppcg;'
  - cp config.default.py config.py
  - sed -i "s/MYSQL_USERNAME/root/" config.py
  - sed -i "s/MYSQL_PASSWORD//" config.py
  - sed -i "s/REDIS_PASSWORD//" config.py
  - sed -i "s/IMGUR_CLIENT_ID/$IMGUR_CLIENT_ID/" config.py
  - sed -i "s/GOOGLE_CLIENT_ID/$GOOGLE_CLIENT_ID/" config.py
  - sed -i "s/BUGSNAG_FRONTEND_API_KEY/$BUGSNAG_FRONTEND_API_KEY/" config.py
  - sed -i "s/BUGSNAG_BACKEND_API_KEY/$BUGSNAG_BACKEND_API_KEY/" config.py
  - celery multi start w1 -A celery_server --logfile=celery.log --pidfile=celery.pid
  - ./build_all.sh
script:
  - coverage run -m unittest discover tests -vf --locals
  - rm celery.pid
  - rm celery.log
after_success:
  - celery multi stop w1 -A celery_server --logfile=celery.log --pidfile=celery.pid
  - codecov
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy/deploy.bash
  on:
    branch: master
after_deploy:
  - bash deploy/docs.bash
before_deploy:
  - openssl aes-256-cbc -K $encrypted_f68e3fa50bfd_key -iv $encrypted_f68e3fa50bfd_iv -in deploy/id_rsa.enc -out deploy/id_rsa -d
